# Generated by Django 5.0.4 on 2024-04-29 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_deadlina_alter_todo_finished_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='deadlina',
            new_name='deadline',
        ),
    ]
